INSERT INTO ING_USER_ADDRESS (ID,STREET,CITY,STATE,POST_CODE)
VALUES ('1','Abercrombie Street','Darlington','NSW','1234');
INSERT INTO ING_USER_ADDRESS (ID,STREET,CITY,STATE,POST_CODE)
VALUES ('2','Burt Street','Darwin City','NT','3413');
INSERT INTO ING_USER_ADDRESS (ID,STREET,CITY,STATE,POST_CODE)
VALUES ('3','Charlotte Street','Brisbane','QlD','4413');
INSERT INTO ING_USER_ADDRESS (ID,STREET,CITY,STATE,POST_CODE)
VALUES ('4','Abercrombie Street','Darlington','NSW','1413'); 
INSERT INTO ING_USER_ADDRESS (ID,STREET,CITY,STATE,POST_CODE)
VALUES ('5','Burt Street','Darwin City','NT','3313');
INSERT INTO ING_USER_ADDRESS (ID,STREET,CITY,STATE,POST_CODE)
VALUES ('6','Charlotte Street','Brisbane','QlD','4613');

INSERT INTO ING_USER (ID,TITLE,FIRST_NAME,GENDER,EMPLOYEE_ID,ING_USER_ADDRESS_ID) 
VALUES ('1','MR','Mark','MALE','1234','1');
INSERT INTO ING_USER (ID,TITLE,FIRST_NAME,GENDER,EMPLOYEE_ID,ING_USER_ADDRESS_ID) 
VALUES ('2','MRS','Jenny','FEMALE','22344','2');
INSERT INTO ING_USER (ID,TITLE,FIRST_NAME,GENDER,EMPLOYEE_ID,ING_USER_ADDRESS_ID) 
VALUES ('3','MRS','Rossie','FEMALE','13234','3');
INSERT INTO ING_USER (ID,TITLE,FIRST_NAME,GENDER,EMPLOYEE_ID,ING_USER_ADDRESS_ID) 
VALUES ('4','MR','Adam','MALE','5234','4');
INSERT INTO ING_USER (ID,TITLE,FIRST_NAME,GENDER,EMPLOYEE_ID,ING_USER_ADDRESS_ID) 
VALUES ('5','MR','Shane','MALE','6234','5');
INSERT INTO ING_USER (ID,TITLE,FIRST_NAME,GENDER,EMPLOYEE_ID,ING_USER_ADDRESS_ID) 
VALUES ('6','MS','Cristy','MALE','6234','6');