INSERT INTO ING_USER_ADDRESS (ID,STREET,CITY,STATE,POST_CODE)
VALUES ('1','Abercrombie Street','Darlington','NSW','1234');
INSERT INTO ING_USER_ADDRESS (ID,STREET,CITY,STATE,POST_CODE)
VALUES ('2','Burt Street','Darwin City','NT','3413');
INSERT INTO ING_USER_ADDRESS (ID,STREET,CITY,STATE,POST_CODE)
VALUES ('3','Charlotte Street','Brisbane','QlD','4413');
INSERT INTO ING_USER_ADDRESS (ID,STREET,CITY,STATE,POST_CODE)
VALUES ('4','Abercrombie Street','Darlington','NSW','1413'); 
INSERT INTO ING_USER_ADDRESS (ID,STREET,CITY,STATE,POST_CODE)
VALUES ('5','Burt Street','Darwin City','NT','3313');
INSERT INTO ING_USER_ADDRESS (ID,STREET,CITY,STATE,POST_CODE)
VALUES ('6','Charlotte Street','Brisbane','QlD','4613');

INSERT INTO ING_USER (ID,TITLE,FIRST_NAME,GENDER,EMPLOYEE_ID,ING_USER_ADDRESS_ID) 
VALUES ('1','mr','test','male','1232854','1');
INSERT INTO ING_USER (ID,TITLE,FIRST_NAME,GENDER,EMPLOYEE_ID,ING_USER_ADDRESS_ID) 
VALUES ('2','mrs','Jenny','female','1232855','2');
INSERT INTO ING_USER (ID,TITLE,FIRST_NAME,GENDER,EMPLOYEE_ID,ING_USER_ADDRESS_ID) 
VALUES ('3','mrs','Rossie','female','1232856','3');
INSERT INTO ING_USER (ID,TITLE,FIRST_NAME,GENDER,EMPLOYEE_ID,ING_USER_ADDRESS_ID) 
VALUES ('4','mr','Adam','male','1232857','4');
INSERT INTO ING_USER (ID,TITLE,FIRST_NAME,GENDER,EMPLOYEE_ID,ING_USER_ADDRESS_ID) 
VALUES ('5','mr','Shane','male','1232858','5');
INSERT INTO ING_USER (ID,TITLE,FIRST_NAME,GENDER,EMPLOYEE_ID,ING_USER_ADDRESS_ID) 
VALUES ('6','ms','Cristy','male','1232859','6');