CREATE TABLE ING_USER_ADDRESS (
  ID          INTEGER PRIMARY KEY,
  STREET VARCHAR(255) NOT NULL,
  CITY   VARCHAR(50) NOT NULL,
  STATE VARCHAR(50) NOT NULL,
  POST_CODE INTEGER NOT NULL);
  
 CREATE TABLE ING_USER(
  ID          INTEGER PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL,
  FIRST_NAME   VARCHAR(50) NOT NULL,
  GENDER VARCHAR(50) NOT NULL,
  EMPLOYEE_ID INTEGER NOT NULL,
  ING_USER_ADDRESS_ID INTEGER,
  FOREIGN KEY (ING_USER_ADDRESS_ID) REFERENCES ING_USER_ADDRESS(ID));
 
    