-- Addres table definition
 CREATE TABLE ING_USER_ADDRESS (
  ID          NUMERIC(19),
  STREET      VARCHAR(255) NOT NULL,
  CITY        VARCHAR(100) NOT NULL,
  STATE       VARCHAR(5) NOT NULL,
  POST_CODE   NUMERIC(10) NOT NULL,
  CREATE_TS   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CHANGE_TS   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
  );
  
 CREATE UNIQUE INDEX PK_ING_USER_ADDRESS ON ING_USER_ADDRESS(ID);
 
-- User table definition
 CREATE TABLE ING_USER(
  ID                   NUMERIC(19) PRIMARY KEY,
  TITLE                VARCHAR(5) NOT NULL,
  FIRST_NAME           VARCHAR(20) NOT NULL,
  GENDER               VARCHAR(6) NOT NULL,
  EMPLOYEE_ID          NUMERIC(10) NOT NULL,
  ING_USER_ADDRESS_ID  NUMERIC(19),
  CREATE_TS            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CHANGE_TS            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
  );
  
 CREATE UNIQUE INDEX PK_ING_USER ON ING_USER(ID);
 
 CREATE UNIQUE INDEX INDEX_ING_EMP_ID ON ING_USER(EMPLOYEE_ID);
 
 ALTER TABLE ING_USER ADD CONSTRAINT UK_ING_EMP_ID UNIQUE (EMPLOYEE_ID);
  
 ALTER TABLE ING_USER ADD FOREIGN KEY (ING_USER_ADDRESS_ID) REFERENCES ING_USER_ADDRESS(ID);
 
    